// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.DAL;

namespace ProductAPI.DAL.Migrations
{
    [DbContext(typeof(AuthorsDbContext))]
    [Migration("20210310050800_seedData")]
    partial class seedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.4")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProductAPI.DAL.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BOD")
                        .HasColumnType("datetime2");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BOD = new DateTime(1981, 3, 10, 8, 8, 0, 256, DateTimeKind.Local).AddTicks(6760),
                            Country = "Iraq",
                            Name = "Author 1"
                        },
                        new
                        {
                            Id = 2,
                            BOD = new DateTime(1971, 3, 10, 8, 8, 0, 257, DateTimeKind.Local).AddTicks(9540),
                            Country = "United States",
                            Name = "Author 2"
                        });
                });

            modelBuilder.Entity("ProductAPI.DAL.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorId = 1,
                            Description = "Book 1 description",
                            IssueDate = new DateTime(2021, 3, 9, 8, 8, 0, 260, DateTimeKind.Local).AddTicks(8722),
                            Name = "Author 1 : Book 1"
                        },
                        new
                        {
                            Id = 2,
                            AuthorId = 1,
                            Description = "Book 2 description",
                            IssueDate = new DateTime(2021, 3, 9, 8, 8, 0, 261, DateTimeKind.Local).AddTicks(43),
                            Name = "Author 1 : Book 2"
                        },
                        new
                        {
                            Id = 3,
                            AuthorId = 2,
                            Description = "Book 1 description",
                            IssueDate = new DateTime(2021, 3, 9, 8, 8, 0, 261, DateTimeKind.Local).AddTicks(73),
                            Name = "Author 2 : Book 1"
                        },
                        new
                        {
                            Id = 4,
                            AuthorId = 2,
                            Description = "Book 2 description",
                            IssueDate = new DateTime(2021, 3, 9, 8, 8, 0, 261, DateTimeKind.Local).AddTicks(77),
                            Name = "Author 2 : Book 2"
                        });
                });

            modelBuilder.Entity("ProductAPI.DAL.Book", b =>
                {
                    b.HasOne("ProductAPI.DAL.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ProductAPI.DAL.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
